version: "3"
services:
  reverseproxy:
      image: jmmarsan/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: jmmarsan/udacity-c3-restapi-user
    environment:
      POSTGRESS_USERNAME: udagramjmdev
      POSTGRESS_PASSWORD: udagramjmdev 
      POSTGRESS_DB: udagramjm
      POSTGRESS_HOST: udagramjmdev.cwxshlyd4pz1.eu-west-2.rds.amazonaws.com 
      AWS_REGION: eu-west-2 
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-jm-dev
      JWT_SECRET: secreto
      URL: "http://localhost:8100"
  backend-feed:
    image: jmmarsan/udacity-c3-restapi-feed
    volumes:
      - C:/Users/Jose/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramjmdev
      POSTGRESS_PASSWORD: udagramjmdev 
      POSTGRESS_DB: udagramjm 
      POSTGRESS_HOST: udagramjmdev.cwxshlyd4pz1.eu-west-2.rds.amazonaws.com 
      AWS_REGION: eu-west-2
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-jm-dev
      JWT_SECRET: secreto
      URL: "http://localhost:8100"
  frontend:
    image: jmmarsan/udacity-c3-frontend
    ports:
      - "8100:80"
